Simulator : {
  DRAM : {
    MemoryMap : {Base : 0x80000000 , Length : 0x10000000}
  },
  Processors : [
    {
      # Processor Architecture Config
      XLEN          : 64,
      SupportISA    : [I,M,A],
      SupportMode   : [M],
      Speculation   : false,
      ForwardResult : true,
      MemoryModel   : SC,
      #------- Micro-Architecure -------#
      iCache : {
        iCacheLatency     : 1,
        iCacheAlignByte   : 32,
      },
      dCache : {
        dCacheLatency     : 1,
        dCacheAlignByte   : 8,
      },
      Rcu : {
        RenameRegister : true,
        AllocWidth     : 8,
        DeallocWidth   : 8,
        ReorderBuffer  : {
          EntryCount   : 128
        },
        PhysicalRegisterFile : {
          Int : {
            RegCount    : 180
          },
        },
        RecoveryPolicy  : {
          RollBack      : true,
          SnapshotCount : 0
        },
      },
      Lsq : {
        LoadQueue : {
          EntryCount   : 72,
        },
        StoreQueue : {
          EntryCount   : 64,
        },
      },
      Resources : {
        RegFileReadPort  : [
          {
            Latency         : 1
          },
          {
            Latency         : 1
          },
          {
            Latency         : 1
          },
          {
            Latency         : 1
          },
          {
            Latency         : 1
          },
          {
            Latency         : 1
          },
          {
            Latency         : 1
          },
          {
            Latency         : 1
          }
        ],
        WriteBackPort : [
          {
            Latency           : 1,
            WakeUpSchedualers : [9,10,11,12,13,14,15,16]
          },
          {
            Latency           : 1,
            WakeUpSchedualers : [9,10,11,12,13,14,15,16]
          },
          {
            Latency           : 1,
            WakeUpSchedualers : [9,10,11,12,13,14,15,16]
          },
          {
            Latency           : 1,
            WakeUpSchedualers : [9,10,11,12,13,14,15,16]
          },
          {
            Latency           : 1,
            WakeUpSchedualers : [9,10,11,12,13,14,15,16]
          },
          {
            Latency           : 1,
            WakeUpSchedualers : [9,10,11,12,13,14,15,16]
          },
          {
            Latency           : 1,
            WakeUpSchedualers : [9,10,11,12,13,14,15,16]
          },
          {
            Latency           : 1,
            WakeUpSchedualers : [9,10,11,12,13,14,15,16]
          }
        ],
        FunctionUnitPool : [
            {Name : CSR0 , FuncType : CSR, Latency : 1, Pipelined : false , WriteBackPort : [0] },

            {Name : LSU0 , FuncType : LSU, Latency : 1, Pipelined : true  , WriteBackPort : [0,1,2,3] },
            {Name : BRU0 , FuncType : BRU, Latency : 1, Pipelined : true  , WriteBackPort : [0,1,2,3] },
            {Name : ALU0 , FuncType : ALU, Latency : 1, Pipelined : true  , WriteBackPort : [0,1,2,3] },
            {Name : ALU1 , FuncType : ALU, Latency : 1, Pipelined : true  , WriteBackPort : [0,1,2,3] },
            {Name : ALU2 , FuncType : ALU, Latency : 1, Pipelined : true  , WriteBackPort : [0,1,2,3] },
            {Name : MUL0 , FuncType : MUL, Latency : 3, Pipelined : true  , WriteBackPort : [0,1,2,3] },
            {Name : MUL1 , FuncType : MUL, Latency : 3, Pipelined : true  , WriteBackPort : [0,1,2,3] },
            {Name : DIV0 , FuncType : DIV, Latency : 7, Pipelined : false , WriteBackPort : [0,1,2,3] },
            
            {Name : LSU1 , FuncType : LSU, Latency : 1, Pipelined : true  , WriteBackPort : [4,5,6,7] },
            {Name : BRU1 , FuncType : BRU, Latency : 1, Pipelined : true  , WriteBackPort : [4,5,6,7] },
            {Name : ALU3 , FuncType : ALU, Latency : 1, Pipelined : true  , WriteBackPort : [4,5,6,7] },
            {Name : ALU4 , FuncType : ALU, Latency : 1, Pipelined : true  , WriteBackPort : [4,5,6,7] },
            {Name : ALU5 , FuncType : ALU, Latency : 1, Pipelined : true  , WriteBackPort : [4,5,6,7] },
            {Name : MUL2 , FuncType : MUL, Latency : 3, Pipelined : true  , WriteBackPort : [4,5,6,7] },
            {Name : MUL3 , FuncType : MUL, Latency : 3, Pipelined : true  , WriteBackPort : [4,5,6,7] },
            {Name : DIV1 , FuncType : DIV, Latency : 7, Pipelined : false , WriteBackPort : [4,5,6,7] }
        ],
        Schedulers : [
            {
              Name             : CSRBuffer,
              EntryCount       : 2,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Order,
              WakeUpPolicy     : Commit,
              RFReadPort       : [0],
              FunctionUnitPool : [0],
              SubScheduler     : []
            },
            {
              Name             : UnifiedDispatchQueue0,
              EntryCount       : 8,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Order ,
              WakeUpPolicy     : RfQueue,
              RFReadPort       : [0],
              FunctionUnitPool : [],
              SubScheduler     : [9]
            },
            {
              Name             : UnifiedDispatchQueue1,
              EntryCount       : 8,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Order ,
              WakeUpPolicy     : RfQueue,
              RFReadPort       : [1],
              FunctionUnitPool : [],
              SubScheduler     : [10]
            },
            {
              Name             : UnifiedDispatchQueue2,
              EntryCount       : 8,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Order ,
              WakeUpPolicy     : RfQueue,
              RFReadPort       : [2],
              FunctionUnitPool : [],
              SubScheduler     : [11]
            },
            {
              Name             : UnifiedDispatchQueue3,
              EntryCount       : 8,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Order ,
              WakeUpPolicy     : RfQueue,
              RFReadPort       : [3],
              FunctionUnitPool : [],
              SubScheduler     : [12]
            },
            {
              Name             : UnifiedDispatchQueue4,
              EntryCount       : 8,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Order ,
              WakeUpPolicy     : RfQueue,
              RFReadPort       : [4],
              FunctionUnitPool : [],
              SubScheduler     : [13]
            },
            {
              Name             : UnifiedDispatchQueue5,
              EntryCount       : 8,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Order ,
              WakeUpPolicy     : RfQueue,
              RFReadPort       : [5],
              FunctionUnitPool : [],
              SubScheduler     : [14]
            },
            {
              Name             : UnifiedDispatchQueue6,
              EntryCount       : 8,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Order ,
              WakeUpPolicy     : RfQueue,
              RFReadPort       : [6],
              FunctionUnitPool : [],
              SubScheduler     : [15]
            },
            {
              Name             : UnifiedDispatchQueue7,
              EntryCount       : 8,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Order ,
              WakeUpPolicy     : RfQueue,
              RFReadPort       : [7],
              FunctionUnitPool : [],
              SubScheduler     : [16]
            },
            {
              Name             : UnifiedIssueQueue0,
              EntryCount       : 4,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Age-Order ,      # In-Order, Out-of-Order, In-Age-Order
              WakeUpPolicy     : ResvrStation,       # None,RfQueue,OperandReady,ResvrStation,Commit
              RFReadPort       : [],
              FunctionUnitPool : [1,2,3,4,5,6,7,8],
              SubScheduler     : []
            },
            {
              Name             : UnifiedIssueQueue1,
              EntryCount       : 4,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Age-Order ,      # In-Order, Out-of-Order, In-Age-Order
              WakeUpPolicy     : ResvrStation,       # None,RfQueue,OperandReady,ResvrStation,Commit
              RFReadPort       : [],
              FunctionUnitPool : [1,2,3,4,5,6,7,8],
              SubScheduler     : []
            },
            {
              Name             : UnifiedIssueQueue2,
              EntryCount       : 4,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Age-Order ,      # In-Order, Out-of-Order, In-Age-Order
              WakeUpPolicy     : ResvrStation,       # None,RfQueue,OperandReady,ResvrStation,Commit
              RFReadPort       : [],
              FunctionUnitPool : [1,2,3,4,5,6,7,8],
              SubScheduler     : []
            },
            {
              Name             : UnifiedIssueQueue3,
              EntryCount       : 4,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Age-Order ,      # In-Order, Out-of-Order, In-Age-Order
              WakeUpPolicy     : ResvrStation,       # None,RfQueue,OperandReady,ResvrStation,Commit
              RFReadPort       : [],
              FunctionUnitPool : [1,2,3,4,5,6,7,8],
              SubScheduler     : []
            },
            {
              Name             : UnifiedIssueQueue4,
              EntryCount       : 4,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Age-Order ,      # In-Order, Out-of-Order, In-Age-Order
              WakeUpPolicy     : ResvrStation,       # None,RfQueue,OperandReady,ResvrStation,Commit
              RFReadPort       : [],
              FunctionUnitPool : [9,10,11,12,13,14,15,16],
              SubScheduler     : []
            },
            {
              Name             : UnifiedIssueQueue5,
              EntryCount       : 4,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Age-Order ,      # In-Order, Out-of-Order, In-Age-Order
              WakeUpPolicy     : ResvrStation,       # None,RfQueue,OperandReady,ResvrStation,Commit
              RFReadPort       : [],
              FunctionUnitPool : [9,10,11,12,13,14,15,16],
              SubScheduler     : []
            },
            {
              Name             : UnifiedIssueQueue6,
              EntryCount       : 4,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Age-Order ,      # In-Order, Out-of-Order, In-Age-Order
              WakeUpPolicy     : ResvrStation,       # None,RfQueue,OperandReady,ResvrStation,Commit
              RFReadPort       : [],
              FunctionUnitPool : [9,10,11,12,13,14,15,16],
              SubScheduler     : []
            },
            {
              Name             : UnifiedIssueQueue7,
              EntryCount       : 4,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Age-Order ,      # In-Order, Out-of-Order, In-Age-Order
              WakeUpPolicy     : ResvrStation,       # None,RfQueue,OperandReady,ResvrStation,Commit
              RFReadPort       : [],
              FunctionUnitPool : [9,10,11,12,13,14,15,16],
              SubScheduler     : []
            },
        ],
      },
      Stages : {
        Fetch1 : {
          Latency   : 1,
          NextStage : Fetch2,
          MaxProcessInsnCount : 16,
          MustTakenAllInsn    : true,
          RedirectLatency     : 1,
          StageInfo : {
            iCacheLatency     : 2,
            iCacheAlignByte   : 32,
            FetchByteWidth    : 32,
            InflightQueueSize : 8,
            BPU               : []
          }
        },
        Fetch2 : {
          Latency   : 1,
          NextStage : Decode,
          MaxProcessInsnCount : 16,
          MustTakenAllInsn    : true,
          RedirectLatency     : 1,
          StageInfo : {
            InstrBufferSize : 32
          }
        },
        Decode : {
          Latency   : 1,
          NextStage : Dispatch,
          MaxProcessInsnCount : 8,
          MustTakenAllInsn    : true,
          RedirectLatency     : -1,
          StageInfo : {
            DecodeQueueSize : 16
          }
        },
        Dispatch : {
          Latency   : 1,
          NextStage : IEW,
          MaxProcessInsnCount : 8,
          MustTakenAllInsn    : false,
          RedirectLatency     : -1,
          StageInfo : {
            Schedulers : [0,1,2,3,4,5,6,7,8]
          }
        },
        IEW : {
          Latency   : 1,
          NextStage : None,
          MaxProcessInsnCount : -1,
          MustTakenAllInsn    : false,
          RedirectLatency     : 1,
          StageInfo : {
          }
        },
        Commit : {
          Latency   : 1,
          NextStage : Commit,
          MaxProcessInsnCount : 8,
          MustTakenAllInsn    : true,
          RedirectLatency     : 1,
          StageInfo : {
          }
        }
      }
    }
  ]
}
