Simulator : {
  DRAM : {
    MemoryMap : {Base : 0x80000000 , Length : 0x10000000}
  },
  Processors : [
    {
      # Processor Architecture Config
      XLEN          : 16,
      SupportISA    : [I,M,C,A],
      SupportMode   : [M],
      Speculation   : false,
      ForwardResult : true,
      MemoryModel   : SC,
      #------- Micro-Architecure -------#
      iCache : {
        iCacheLatency     : 1,
        iCacheAlignByte   : 8,
      },
      dCache : {
        dCacheLatency     : 1,
        dCacheAlignByte   : 8,
      },
      Rcu : {
        RenameRegister : true,
        AllocWidth     : 2,
        DeallocWidth   : 2,
        ReorderBuffer  : {
          EntryCount   : 48
        },
        PhysicalRegisterFile : {
          Int : {
            RegCount    : 48
          },
        },
        RecoveryPolicy  : {
          RollBack      : true,
          SnapshotCount : 0
        },
      },
      Lsq : {
        LoadQueue : {
          EntryCount   : 16,
        },
        StoreQueue : {
          EntryCount   : 8,
        },
      },
      Resources : {
        RegFileReadPort  : [
          {
            Latency         : 1
          },
          {
            Latency         : 1
          },
        ],
        WriteBackPort : [
          {
            Latency           : 1,
            WakeUpSchedualers : [3,4]
          },
          {
            Latency           : 1,
            WakeUpSchedualers : [3,4]
          },
        ],
        FunctionUnitPool : [
            {Name : CSR0 , FuncType : CSR, Latency : 1, Pipelined : false , WriteBackPort : [0] },

            {Name : LSU0 , FuncType : LSU, Latency : 1, Pipelined : true  , WriteBackPort : [0,1] },
            {Name : BRU0 , FuncType : BRU, Latency : 1, Pipelined : true  , WriteBackPort : [0,1] },
            {Name : ALU0 , FuncType : ALU, Latency : 1, Pipelined : true  , WriteBackPort : [0,1] },
            {Name : ALU1 , FuncType : ALU, Latency : 1, Pipelined : true  , WriteBackPort : [0,1] },
            {Name : MUL0 , FuncType : MUL, Latency : 3, Pipelined : true  , WriteBackPort : [0,1] },
            {Name : DIV0 , FuncType : DIV, Latency : 7, Pipelined : false , WriteBackPort : [0,1] },
        ],
        Schedulers : [
            {
              Name             : CSRBuffer,
              EntryCount       : 2,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Order,
              WakeUpPolicy     : Commit,
              RFReadPort       : [0],
              FunctionUnitPool : [0],
              SubScheduler     : []
            },
            {
              Name             : UnifiedDispatchQueue0,
              EntryCount       : 8,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Order ,
              WakeUpPolicy     : RfQueue,
              RFReadPort       : [0],
              FunctionUnitPool : [],
              SubScheduler     : [3]
            },
            {
              Name             : UnifiedDispatchQueue1,
              EntryCount       : 8,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Order ,
              WakeUpPolicy     : RfQueue,
              RFReadPort       : [1],
              FunctionUnitPool : [],
              SubScheduler     : [4]
            },
            {
              Name             : UnifiedIssueQueue0,
              EntryCount       : 4,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Age-Order ,      # In-Order, Out-of-Order, In-Age-Order
              WakeUpPolicy     : ResvrStation,       # None,RfQueue,OperandReady,ResvrStation,Commit
              RFReadPort       : [],
              FunctionUnitPool : [1],
              SubScheduler     : []
            },
            {
              Name             : UnifiedIssueQueue1,
              EntryCount       : 4,
              EnqueWidth       : 1,
              DequeWidth       : 1,
              IssuePolicy      : In-Age-Order ,      # In-Order, Out-of-Order, In-Age-Order
              WakeUpPolicy     : ResvrStation,       # None,RfQueue,OperandReady,ResvrStation,Commit
              RFReadPort       : [],
              FunctionUnitPool : [2,3,4,5,6],
              SubScheduler     : []
            },
        ],
      },
      Stages : {
        Fetch1 : {
          Latency   : 1,
          NextStage : Fetch2,
          MaxProcessInsnCount : 4,
          MustTakenAllInsn    : true,
          RedirectLatency     : 1,
          StageInfo : {
            iCacheLatency     : 2,
            iCacheAlignByte   : 8,
            FetchByteWidth    : 8,
            InflightQueueSize : 8,
            BPU               : []
          }
        },
        Fetch2 : {
          Latency   : 1,
          NextStage : Decode,
          MaxProcessInsnCount : 4,
          MustTakenAllInsn    : true,
          RedirectLatency     : 1,
          StageInfo : {
            InstrBufferSize : 16
          }
        },
        Decode : {
          Latency   : 1,
          NextStage : Dispatch,
          MaxProcessInsnCount : 2,
          MustTakenAllInsn    : true,
          RedirectLatency     : -1,
          StageInfo : {
            DecodeQueueSize : 16
          }
        },
        Dispatch : {
          Latency   : 1,
          NextStage : IEW,
          MaxProcessInsnCount : 2,
          MustTakenAllInsn    : false,
          RedirectLatency     : -1,
          StageInfo : {
            Schedulers : [0,1,2]
          }
        },
        IEW : {
          Latency   : 1,
          NextStage : None,
          MaxProcessInsnCount : -1,
          MustTakenAllInsn    : false,
          RedirectLatency     : 1,
          StageInfo : {
          }
        },
        Commit : {
          Latency   : 1,
          NextStage : Commit,
          MaxProcessInsnCount : 2,
          MustTakenAllInsn    : true,
          RedirectLatency     : 1,
          StageInfo : {
          }
        }
      }
    }
  ]
}
